---
title: "Scratch Code"
format: pdf
editor: visual
---

### Question 1: Using `GET` from the `httr` Package to Pull News Info

```{r, warning=FALSE, message=FALSE}
#Loading required packages
library("httr")

#Using httr::GET to collect information about the nba in the news
nba_info <- httr::GET("https://v2.nba.api-sports.io/everything?x-rapidapi-key=9086777ffcmsh8e20ab7c07d978ep14073cjsndbf0615eb5ec")
nba_info
```

```{r}
url <- "https://api-nba-v1.p.rapidapi.com/players/statistics"
# game = "8133"
queryString <- list(game = "8133")

response <- VERB("GET", url, query = queryString, add_headers('x-rapidapi-key' = '9086777ffcmsh8e20ab7c07d978ep14073cjsndbf0615eb5ec', 'x-rapidapi-host' = 'api-nba-v1.p.rapidapi.com'), content_type("application/octet-stream"))

response <- httr::GET(url, 
                      add_headers('x-rapidapi-key' = '9086777ffcmsh8e20ab7c07d978ep14073cjsndbf0615eb5ec', 
                                  'x-rapidapi-host' = 'api-nba-v1.p.rapidapi.com'),
                      content_type("application/octet-stream"))

content(response, "text")

# use this link to see R code for API queries: https://rapidapi.com/api-sports/api/api-nba
# could also try accessing data from Basketball Reference? mentioned in CSAS powerpoint
```